/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicalUI;

import airlinePkg.Airline;
import foodPkg.Food;
import foodPkg.FoodMenu;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import peoplePkg.Passenger;

/**
 *
 * @author Jimmy
 */
public class AddPForm2 extends javax.swing.JFrame {

    /**
     * Creates new form AddPForm2
     */
    
    JFrame mainFrame;
    //AddPassengerForm g = new AddPassengerForm();
    //MainMenuGraphical mmg = new MainMenuGraphical();
    MainMGraphical2 mmg = new MainMGraphical2();

    Food[] foods = new Food[12];
    FoodMenu fMenu;// = new FoodMenu();
    ArrayList<Food> foodlist = new ArrayList<>(6);

    Airline airline = new Airline();

    JFrame thisGraficalFrame;
    
    //la till denna april 2018 för rull-listans ifyllning beroende på sätena
    boolean seatIsBooked;
    //la också till(flyttade från btnTicket) denna april 2018
    String name;
    
    public AddPForm2() {
        foods[0] = new Food(110, "Entrecote");
        foods[1] = new Food(95, "Jasmineris");
        foods[2] = new Food(85, "Angusburger");
        foods[3] = new Food(20, "Monster energy drink");
        foods[4] = new Food(115, "Champagne");
        foods[5] = new Food(40, "Café au lait");

        foods[6] = new Food(55, "Meatballs");
        foods[7] = new Food(65, "Spaghetti");
        foods[8] = new Food(50, "Hamburger");
        foods[9] = new Food(15, "Soft drink");
        foods[10] = new Food(85, "Wine");
        foods[11] = new Food(30, "Coffee");
        
        initComponents();
        
        createUIComponents();
        
        //la till raden under april 2018        
        this.setBounds(500, 0, 500, 650);
        
        this.setTitle("Add passenger");
        this.setVisible(false);

        this.mmg.setGraficalFrame(this);
        this.setThisGraficalFrame(this);
        
        this.mmg.setVisible(true);
        
        //this.mainFrame = new JFrame("Airline project graphical");
        //this.mainFrame.setContentPane(this.mmg.getMainPanel());
        //this.mainFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpClass = new javax.swing.ButtonGroup();
        huvudPanel = new javax.swing.JPanel();
        jmAirlinesLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSeatNr = new javax.swing.JLabel();
        btnTicket = new javax.swing.JButton();
        btnAirline = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        economyClassRadioButton = new javax.swing.JRadioButton();
        textfSurname = new javax.swing.JTextField();
        textfieldFirstName = new javax.swing.JTextField();
        cboDestinations = new javax.swing.JComboBox<>();
        firstClassRadioButton = new javax.swing.JRadioButton();
        spnAge = new javax.swing.JSpinner();
        köttbullarCheckBox = new javax.swing.JCheckBox();
        läskCheckbox = new javax.swing.JCheckBox();
        spaghettiCheckBox = new javax.swing.JCheckBox();
        vinCheckBox = new javax.swing.JCheckBox();
        hamburgareCheckBox = new javax.swing.JCheckBox();
        kaffeCheckbox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTicket = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAirline = new javax.swing.JTextArea();
        cboSeatNr = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        huvudPanel.setLayout(new java.awt.GridLayout(22, 5));

        jmAirlinesLabel.setText("Passenger information");
        huvudPanel.add(jmAirlinesLabel);

        jLabel2.setText("Destination");
        huvudPanel.add(jLabel2);

        jLabel1.setText("First name");
        huvudPanel.add(jLabel1);

        jLabel3.setText("Surname");
        huvudPanel.add(jLabel3);

        jLabel4.setText("Age");
        huvudPanel.add(jLabel4);

        jLabel5.setText("Class");
        huvudPanel.add(jLabel5);

        jLabel6.setText("Food");
        huvudPanel.add(jLabel6);

        lblSeatNr.setText("Seat number");
        huvudPanel.add(lblSeatNr);

        btnTicket.setText("Print Ticket");
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });
        huvudPanel.add(btnTicket);

        btnAirline.setText("Airline");
        btnAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlineActionPerformed(evt);
            }
        });
        huvudPanel.add(btnAirline);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        huvudPanel.add(btnSave);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        huvudPanel.add(btnBack);

        btnGrpClass.add(economyClassRadioButton);
        economyClassRadioButton.setText("Economy class");
        economyClassRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economyClassRadioButtonActionPerformed(evt);
            }
        });

        textfSurname.setColumns(1);
        textfSurname.setText("textfSurname");

        textfieldFirstName.setColumns(2);
        textfieldFirstName.setText("textfieldFirstName");

        cboDestinations.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGrpClass.add(firstClassRadioButton);
        firstClassRadioButton.setText("First class");
        firstClassRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstClassRadioButtonActionPerformed(evt);
            }
        });

        köttbullarCheckBox.setText("Köttbullar");

        läskCheckbox.setText("Läsk");

        spaghettiCheckBox.setText("Spaghetti");

        vinCheckBox.setText("Vin");

        hamburgareCheckBox.setText("Hamburgare");

        kaffeCheckbox.setText("Kaffe");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 50));

        txtTicket.setColumns(20);
        txtTicket.setRows(5);
        jScrollPane1.setViewportView(txtTicket);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(150, 50));

        textAirline.setColumns(20);
        textAirline.setRows(5);
        jScrollPane2.setViewportView(textAirline);

        cboSeatNr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(huvudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboDestinations, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(firstClassRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(economyClassRadioButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textfSurname, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textfieldFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(köttbullarCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(läskCheckbox))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spaghettiCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(vinCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hamburgareCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kaffeCheckbox))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSeatNr, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1033, 1033, 1033))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(huvudPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cboDestinations, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(textfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(economyClassRadioButton)
                    .addComponent(firstClassRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(köttbullarCheckBox)
                    .addComponent(läskCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spaghettiCheckBox)
                    .addComponent(vinCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hamburgareCheckBox)
                    .addComponent(kaffeCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboSeatNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        int age = (int) spnAge.getValue();
        String flightClass = "";
        if (firstClassRadioButton.isSelected() == true) {
            flightClass = "First Class";
        } else {
            flightClass = "Economy Class";
        }

        int seatNr = Integer.parseInt(cboSeatNr.getSelectedItem().toString());
        makeMenu();

        String ticket = "Ticket to: " + cboDestinations.getSelectedItem().toString() + "\n";
        ticket = ticket + "Name: " + name + "\n";
        ticket = ticket + "Age: " + age + "\n";
        ticket = ticket + "Seat number: " + seatNr + "\n";
        ticket = ticket + "Class: " + flightClass + "\n";
        ticket = ticket + "Food: " + "\n";
        for (Food f : fMenu.getFoodList()) {
            ticket = ticket + f.getFoodTitel() + ": " + f.getPrice() + " SEK" + "\n";
        }
        txtTicket.setText(ticket);
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlineActionPerformed
        textAirline.setText("");
        String printOut = "JM Airlines " + "\n";
        printOut = printOut + "Airline's income: " + airline.getAirlineIncome() + "\n";
        printOut = printOut + "Airline's profit: " + airline.getAirlineProfit();
        textAirline.setText(printOut);
    }//GEN-LAST:event_btnAirlineActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String fName = textfieldFirstName.getText();
        String lName = textfSurname.getText();
        name = fName + " " + lName;//för btnTicket, la till april 2018
        int age = (int) spnAge.getValue();
        int seatNr = Integer.parseInt(cboSeatNr.getSelectedItem().toString());
        String dest = cboDestinations.getSelectedItem().toString();
        int totP = 0;

        makeMenu();
        airline.addFoodIncome(fMenu.getTotalFoodPrice());

        if (seatNr < 6) {
            totP = 20000 + fMenu.getTotalFoodPrice();
        } else {
            totP = 5000 + fMenu.getTotalFoodPrice();
        }
        Passenger p = new Passenger(fName, lName, totP, seatNr, dest, age);
        mmg.addPassAndSeat(p, fMenu);

        airline.calculateProfitAndIncome(totP);
        mmg.setaLine(airline);
        
        //la jag till april 2018
        resetMenuOptions();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        getThisGraficalFrame().setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void firstClassRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstClassRadioButtonActionPerformed
        //la jag till april 2018
        enableMenuOptions();
        
        köttbullarCheckBox.setText("Entrecote");
        spaghettiCheckBox.setText("Jasminerice");
        hamburgareCheckBox.setText("Angusburger");

        läskCheckbox.setText("Monster energy drink");
        vinCheckBox.setText("Champagne");
        kaffeCheckbox.setText("Café au lait");
        
        String dest = cboDestinations.getSelectedItem().toString();        
        String[] nrs = {"1", "2", "3", "4", "5"};        
        cboSeatNr.removeAllItems();
        for (int j = 0; j < 5; j++) {
            seatIsBooked = mmg.getIfSeatIsBooked(dest, j);
            if (seatIsBooked == false) {
                cboSeatNr.addItem(nrs[j]);
            }
        }
    }//GEN-LAST:event_firstClassRadioButtonActionPerformed

    private void economyClassRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economyClassRadioButtonActionPerformed
        //la jag till april 2018
        enableMenuOptions();
        
        köttbullarCheckBox.setText("Meatballs");
        spaghettiCheckBox.setText("Spaghetti");
        hamburgareCheckBox.setText("Hamburger");

        läskCheckbox.setText("Soft drink");
        vinCheckBox.setText("Wine");
        kaffeCheckbox.setText("Coffee");
        
        String dest = cboDestinations.getSelectedItem().toString();
        String[] nrs = {"6", "7", "8", "9", "10"};        
        cboSeatNr.removeAllItems();
        for (int j = 0; j < 5; j++) {
            seatIsBooked = mmg.getIfSeatIsBooked(dest, j + 5);
            if (seatIsBooked == false) {
                cboSeatNr.addItem(nrs[j]);
            }
        }
    }//GEN-LAST:event_economyClassRadioButtonActionPerformed

    //alla "grejer" med alternativet "Custom create" måste jag skapa här
    private void createUIComponents() {
        //huvudPanel = new JPanel();//JScrollPane
        //huvudPanel.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        /*jmAirlinesLabel = new JLabel("JM Airlines");
        huvudPanel.add(jmAirlinesLabel);*/

        //JOptionPane.showConfirmDialog(AddPassengerForm.this, "Ny dialog form");
        /*cboDestinations.addItem("London");
        cboDestinations.addItem("Paris");
        cboDestinations.addItem("Rome");
        cboDestinations.addItem("Miami");*/

        //textfieldFirstName = new JTextField("");
        //textfSurname = new JTextField("");
        
        //la jag till dessa 2 rader april 2018
        resetMenuOptions();
        btnSave.setText("Book passenger");
        
        SpinnerModel model = new SpinnerNumberModel(25, 1, 120, 1);
        //spnAge = new JSpinner(model);
        spnAge.setModel(model);
        spnAge.setSize(10, 8);

        /*firstClassRadioButton = new JRadioButton();
        economyClassRadioButton = new JRadioButton();
        köttbullarCheckBox = new JCheckBox();*/

        //denna valde jag inte "custom create" på, men ska kanske
        String[] orter = {"London", "Paris", "Rome", "Miami"};
        //cboDestinations = new JComboBox(orter);
        
        cboDestinations.removeAllItems();
        for (int i = 0; i < 4; i++) {
            cboDestinations.addItem(orter[i]);
        }

        //cboSeatNr = new JComboBox(nrs);
        
        /*String[] nrs = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10"};        
        cboSeatNr.removeAllItems();
        for (int j = 0; j < 10; j++) {
            cboSeatNr.addItem(nrs[j]);
        }*/
    }

    private void makeMenu(){
        foodlist.clear();
        if(köttbullarCheckBox.isSelected() == true && firstClassRadioButton.isSelected() == true){
            //fMenu //add food
            foodlist.add(foods[0]);
        }

        if(spaghettiCheckBox.isSelected() == true && firstClassRadioButton.isSelected() == true){
            foodlist.add(foods[1]);
        }

        if(hamburgareCheckBox.isSelected() == true && firstClassRadioButton.isSelected() == true){
            foodlist.add(foods[2]);
        }

        if(läskCheckbox.isSelected() == true && firstClassRadioButton.isSelected() == true){
            foodlist.add(foods[3]);
        }

        if(vinCheckBox.isSelected() == true && firstClassRadioButton.isSelected() == true){
            foodlist.add(foods[4]);
        }

        if(kaffeCheckbox.isSelected() == true && firstClassRadioButton.isSelected() == true){
            foodlist.add(foods[5]);
        }

        if(köttbullarCheckBox.isSelected() == true && firstClassRadioButton.isSelected() == false){
            foodlist.add(foods[6]);
        }

        if(spaghettiCheckBox.isSelected() == true && firstClassRadioButton.isSelected() == false){
            foodlist.add(foods[7]);
        }

        if(hamburgareCheckBox.isSelected() == true && firstClassRadioButton.isSelected() == false){
            foodlist.add(foods[8]);
        }

        if(läskCheckbox.isSelected() == true && firstClassRadioButton.isSelected() == false){
            foodlist.add(foods[9]);
        }

        if(vinCheckBox.isSelected() == true && firstClassRadioButton.isSelected() == false){
            foodlist.add(foods[10]);
        }

        if(kaffeCheckbox.isSelected() == true && firstClassRadioButton.isSelected() == false){
            foodlist.add(foods[11]);
        }

        fMenu = new FoodMenu(foodlist);
    }
    
    //ny hjälp-metod april 2018
    private void resetMenuOptions() {
        textfieldFirstName.setText("");
        textfSurname.setText("");
        
        köttbullarCheckBox.setEnabled(false);
        spaghettiCheckBox.setEnabled(false);
        hamburgareCheckBox.setEnabled(false);

        läskCheckbox.setEnabled(false);
        vinCheckBox.setEnabled(false);
        kaffeCheckbox.setEnabled(false);
        
        cboSeatNr.setEnabled(false);
    }
    
    //ny hjälp-metod april 2018
    private void enableMenuOptions() {
        köttbullarCheckBox.setEnabled(true);
        spaghettiCheckBox.setEnabled(true);
        hamburgareCheckBox.setEnabled(true);

        läskCheckbox.setEnabled(true);
        vinCheckBox.setEnabled(true);
        kaffeCheckbox.setEnabled(true);
        
        cboSeatNr.setEnabled(true);
    }

    public JPanel getHuvudPanel() {
        return huvudPanel;
    }

    public void showGrafical(){
        this.setVisible(true);
    }

    public JFrame getThisGraficalFrame() {
        return thisGraficalFrame;
    }

    public void setThisGraficalFrame(JFrame thisGraficalFrame) {
        this.thisGraficalFrame = thisGraficalFrame;
    }
        
    public static void main(String args[]) {
                
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AddPForm2().setVisible(true);
                
                AddPForm2 g = new AddPForm2(); //g //apf2

                //JFrame frame = new JFrame("Add passenger");
                /*frame.setContentPane(g.huvudPanel);//new AddPassengerForm()
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setSize(400, 600);
                frame.setLocation(350, 0);
                frame.setVisible(false);*/
                
                //g.mmg.setGraficalFrame(frame);//la jag till så man kan öppna detta fönster från huvudfönstret
                //g.setThisGraficalFrame(frame);
                
                //g.mmg.setAPF2(g);//feb 2018

                //kan göra "JFrame mainFrame" på klass-nivå så jag kommer åt den från btnSave
                //MainMenuGraphical mmg = new MainMenuGraphical();
                //g.mainFrame = new JFrame("Airline project graphical");//JFrame
                //g.mainFrame.setContentPane(g.mmg.getMainPanel());//new MainMenuGraphical()
                //g.mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                //g.mainFrame.pack();
                //g.mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirline;
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup btnGrpClass;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTicket;
    private javax.swing.JComboBox<String> cboDestinations;
    private javax.swing.JComboBox<String> cboSeatNr;
    private javax.swing.JRadioButton economyClassRadioButton;
    private javax.swing.JRadioButton firstClassRadioButton;
    private javax.swing.JCheckBox hamburgareCheckBox;
    private javax.swing.JPanel huvudPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jmAirlinesLabel;
    private javax.swing.JCheckBox kaffeCheckbox;
    private javax.swing.JCheckBox köttbullarCheckBox;
    private javax.swing.JLabel lblSeatNr;
    private javax.swing.JCheckBox läskCheckbox;
    private javax.swing.JCheckBox spaghettiCheckBox;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JTextArea textAirline;
    private javax.swing.JTextField textfSurname;
    private javax.swing.JTextField textfieldFirstName;
    private javax.swing.JTextArea txtTicket;
    private javax.swing.JCheckBox vinCheckBox;
    // End of variables declaration//GEN-END:variables
}
