/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicalUI;

import airplanePkg.Airplane;
import java.awt.BorderLayout;
import java.awt.Cursor;
//import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JProgressBar;

/**
 *
 * @author Jimmy
 */
public class FlyForm2 extends javax.swing.JFrame {//implements ActionListener

    /**
     * Creates new form FlyForm2
     */
    
    ArrayList<Airplane> planes = new ArrayList<>(4);
    
    public FlyForm2() {
        initComponents();
        createUIComponents();        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flyingFormWindow = new javax.swing.JPanel();
        flygPanel = new javax.swing.JPanel();
        textPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        planeTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnFly = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        flyingFormWindow.setLayout(new java.awt.GridLayout(4, 2));

        flygPanel.setLayout(new java.awt.GridLayout(1, 1));
        flyingFormWindow.add(flygPanel);

        textPanel.setLayout(new java.awt.GridLayout());

        planeTextArea.setColumns(20);
        planeTextArea.setRows(5);
        jScrollPane1.setViewportView(planeTextArea);

        textPanel.add(jScrollPane1);

        flyingFormWindow.add(textPanel);

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        btnFly.setText("Fly");
        btnFly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlyActionPerformed(evt);
            }
        });
        jPanel1.add(btnFly);

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        jPanel1.add(returnButton);

        flyingFormWindow.add(jPanel1);
        flyingFormWindow.add(progressBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flyingFormWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flyingFormWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlyActionPerformed
        flygPanel.setLayout(new BorderLayout());
        flygPanel.setVisible(true);
        FlightClass fc = new FlightClass();
        //JButton jb = new JButton("hello");

        //flygPanel.setVisible(true);//flyttar ovanför FlightClass ovan april 2018
        //flygPanel.add(jb, BorderLayout.EAST);
        flygPanel.add(fc, BorderLayout.CENTER);

        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        //Task task = new Task();//javax.swing.SwingWorker.

        //planeTextArea.setText(planes.get(0).returnPassengerList() + "\n" + planes.get(1).returnPassengerList() + "\n"
        //      + planes.get(2).returnPassengerList() + "\n" + planes.get(3).returnPassengerList() + "\n");
        //ProgressBarClass pbc = new ProgressBarClass();
        
        //testar att kommentera bort detta april 2018
        /*ProgBarClass pbc = new ProgBarClass();//ändra till denna feb 2018
        pbc.execute();

        JFrame frame = new JFrame();
        frame.setContentPane(pbc.getProgressClassMainPanel());//new ProgressBarClass()
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(400, 300);
        frame.setLocation(350, 100);
        frame.setVisible(true);*/

        //flyttade dom hit för att testa april 2018
        planeTextArea.setText(planeTextArea.getText() + "\n" + "\n" + "Blue plane to " + planes.get(0).getDestination());
        planeTextArea.setText(planeTextArea.getText() + "\n" + "\n" + "Red plane to " + planes.get(1).getDestination());
        planeTextArea.setText(planeTextArea.getText() + "\n" + "\n" + "Green plane to " + planes.get(2).getDestination());
        planeTextArea.setText(planeTextArea.getText() + "\n" + "\n" + "Cyan plane to " + planes.get(3).getDestination());
        
        int prog = 0;
        for (int i = 0; i < 10; i++) {
            try {
                Thread.sleep(1000);
                
                //dessa rader uppflyttade från under try-catch april 2018
                progressBar.setValue(prog);//10
                prog = prog + 10;//4700;//10;
                progressBar.updateUI();
                planeTextArea.setText(planeTextArea.getText() + "plane has flown " + prog + " %" + "\n");
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
            

            //fc.repaint();
            //flygPanel.repaint();           
        }
        /*planeTextArea.setText(planeTextArea.getText() + "\n" + "\n" + "Blue plane to " + planes.get(0).getDestination());
        planeTextArea.setText(planeTextArea.getText() + "\n" + "\n" + "Red plane to " + planes.get(1).getDestination());
        planeTextArea.setText(planeTextArea.getText() + "\n" + "\n" + "Green plane to " + planes.get(2).getDestination());
        planeTextArea.setText(planeTextArea.getText() + "\n" + "\n" + "Cyan plane to " + planes.get(3).getDestination());*/
        
        fc.startFlightTimer();//april 2018
        
        //FlyingForm3 ff3 = new FlyingForm3();
        //ff3.setPlanes(planes);
    }//GEN-LAST:event_btnFlyActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        getFlyingFormWindow().setVisible(false);
    }//GEN-LAST:event_returnButtonActionPerformed

    public JPanel getFlygPanel() {
        return flygPanel;
    }

    public void setFlygPanel(JPanel flygPanel) {
        this.flygPanel = flygPanel;
    }

    public JPanel getFlyingFormWindow() {
        return flyingFormWindow;
    }

    public void setFlyingFormWindow(JPanel flyingFormWindow) {
        this.flyingFormWindow = flyingFormWindow;
    }

    public void setPlanes(ArrayList<Airplane> planes) {
        this.planes = planes;
    }

    private void createUIComponents() {        
        //progressBar = new JProgressBar(0, 47000);//detta orsakar felet med att man inte ser nya värdet jag sätter. 10 är för litet. Blir inte procent p g a detta.
        //progressBar.setValue(0);
        progressBar.setMinimum(0);
        progressBar.setMaximum(47000);
        
        progressBar.setStringPainted(true);
        //progressBar.setIndeterminate(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFly;
    private javax.swing.JPanel flygPanel;
    private javax.swing.JPanel flyingFormWindow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea planeTextArea;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton returnButton;
    private javax.swing.JPanel textPanel;
    // End of variables declaration//GEN-END:variables
}
