/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicalUI;

import airlinePkg.Airline;
import airplanePkg.Airplane;
import airplanePkg.Seat;
import foodPkg.FoodMenu;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import peoplePkg.Passenger;
import servicesPkg.CheckingPlane;

/**
 *
 * @author Jimmy
 */
public class MainMGraphical2 extends javax.swing.JFrame {

    /**
     * Creates new form MainMGraphical2
     * MainMenuGraphical redone...
     * ...because it was done in IntelliJ...
     * ...and form didn't work here
     * Copied the code, but did the graphical again
     */
    
    /*private JButton btnAddPass;
    private JButton btnAirlineInfo;
    private JButton btnFlyAirplanes;
    private JButton btnExit;
    private JPanel mainPanel;
    private JComboBox cboDestination;
    private JLabel lblDestination;
    private JButton fillPlaneButton;
    private JButton fillPlaneWithRealButton;*/

    ArrayList<Airplane> planes = new ArrayList<>(4);
    Passenger passenger;
    Seat s;

    Airline aLine = new Airline();

    CheckingPlane checkPlane = new CheckingPlane();

    JFrame graficalFrame;
    
    //la jag till feb 2018
    //AddPForm2 apf2 = new AddPForm2();
    
    public MainMGraphical2() {
        planes.add(new Airplane());
        planes.add(new Airplane());
        planes.add(new Airplane());
        planes.add(new Airplane());

        planes.get(0).setDestination("London");
        planes.get(1).setDestination("Paris");
        planes.get(2).setDestination("Rome");
        planes.get(3).setDestination("Miami");

        planes.get(0).setName("AA11");
        planes.get(1).setName("UA175");
        planes.get(2).setName("AA77");
        planes.get(3).setName("UA93");
        
        initComponents();
        
        createUIComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        btnAddPass = new javax.swing.JButton();
        btnAirlineInfo = new javax.swing.JButton();
        btnFlyAirplanes = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblDestination = new javax.swing.JLabel();
        cboDestination = new javax.swing.JComboBox<>();
        fillPlaneButton = new javax.swing.JButton();
        fillPlaneWithRealButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.GridLayout(4, 2));

        btnAddPass.setText("Add Passenger");
        btnAddPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPassActionPerformed(evt);
            }
        });
        mainPanel.add(btnAddPass);

        btnAirlineInfo.setText("Airline info");
        btnAirlineInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlineInfoActionPerformed(evt);
            }
        });
        mainPanel.add(btnAirlineInfo);

        btnFlyAirplanes.setText("Fly airplanes");
        btnFlyAirplanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlyAirplanesActionPerformed(evt);
            }
        });
        mainPanel.add(btnFlyAirplanes);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        mainPanel.add(btnExit);

        lblDestination.setText("Airplane destination");
        mainPanel.add(lblDestination);
        lblDestination.getAccessibleContext().setAccessibleDescription("");

        cboDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mainPanel.add(cboDestination);

        fillPlaneButton.setText("Fill plane");
        fillPlaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillPlaneButtonActionPerformed(evt);
            }
        });
        mainPanel.add(fillPlaneButton);

        fillPlaneWithRealButton.setText("Fill plane with real people(London)");
        fillPlaneWithRealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillPlaneWithRealButtonActionPerformed(evt);
            }
        });
        mainPanel.add(fillPlaneWithRealButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillPlaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillPlaneButtonActionPerformed
        String dest = cboDestination.getSelectedItem().toString();
        if (dest.equalsIgnoreCase("London") == true) {
            //planes.get(0).fillPassengersWithRealPeople();
            planes.get(0).fillPassengersOnPlane();
        } else if (dest.equalsIgnoreCase("Paris") == true) {
            planes.get(1).fillPassengersOnPlane();
        } else if (dest.equalsIgnoreCase("Rome") == true) {
            planes.get(2).fillPassengersOnPlane();
        } else if (dest.equalsIgnoreCase("Miami") == true) {
            planes.get(3).fillPassengersOnPlane();
        }
    }//GEN-LAST:event_fillPlaneButtonActionPerformed

    private void fillPlaneWithRealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillPlaneWithRealButtonActionPerformed
        //String dest = cboDestination.getSelectedItem().toString();
        //if(dest.equalsIgnoreCase("London") == true) {
            planes.get(0).fillPassengersWithRealPeople();
        //}
    }//GEN-LAST:event_fillPlaneWithRealButtonActionPerformed

    private void btnFlyAirplanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlyAirplanesActionPerformed
        //skicka plan-arraylist
        //FlyingForm ff = new FlyingForm();
        FlyForm2 ff = new FlyForm2();
        ff.setPlanes(planes);

        //öppna nytt fönster för flygning
        //FlyingForm ff = new FlyingForm();
        JFrame frame = new JFrame("Fly airplanes");
        frame.setContentPane(ff.getFlyingFormWindow());//.getFlygPanel()//new FlyingForm()

        //frame.add(new FlyingForm().getFlygPanel());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(600, 700);
        //frame.pack();
        frame.setLocation(750, 0);
        frame.setVisible(true);
        
        FlyingForm3 ff3 = new FlyingForm3();
        ff3.setPlanes(planes);
    }//GEN-LAST:event_btnFlyAirplanesActionPerformed

    private void btnAirlineInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlineInfoActionPerformed
        //AirlineInfoForm aiForm = new AirlineInfoForm();
        ALInfoForm2 aiForm = new ALInfoForm2();
        aiForm.setAirline(aLine);
        aiForm.setPlanes(planes);
        aiForm.setVisible(true);//feb 2018
        aiForm.setLocation(750, 0);

        //JFrame jf = new JFrame();
        //jf.setContentPane(aiForm.getAirlineMainPanel());
        //jf.setSize(400, 700);
        //jf.setLocation(750, 0);
        //jf.setVisible(true);

        aiForm.setThisAirlineInfoFrame(aiForm);//jf//feb 2018
    }//GEN-LAST:event_btnAirlineInfoActionPerformed

    private void btnAddPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPassActionPerformed
        getGraficalFrame().setVisible(true);
        
        //this.getAPF2().setVisible(true);
        
        //testar
        //AddPForm2 apf2 = new AddPForm2();
        //apf2.getThisGraficalFrame().setVisible(true);
    }//GEN-LAST:event_btnAddPassActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    public void addPassAndSeat(Passenger p, FoodMenu fm){
        passenger = p;

        // = new Passenger(firstName, surname, totalTicketPrice, seat.getSeatNumber(), airPlanes[noOfPlane].getDestination(), age);
        //seat.setPassenger(p);
        //airPlanes[noOfPlane].addSeatAndPass(seat, p);

        s = new Seat(p.getSeatNr(), p, fm);
        //s.setPassenger(passenger);//gör allt i Seat
        if(p.getDestination().equalsIgnoreCase("London") == true){
            planes.get(0).addSeatAndPass(s, passenger);

            boolean full = checkPlane.isPlaneFullyBooked(planes.get(0));

            if(full == true){
                btnAddPass.setEnabled(false);//kan inte boka om planet är fullt
            }
        }
        else if(p.getDestination().equalsIgnoreCase("Paris") == true){
            planes.get(1).addSeatAndPass(s, passenger);
            boolean full = checkPlane.isPlaneFullyBooked(planes.get(1));

            if(full == true){
                btnAddPass.setEnabled(false);//kan inte boka om planet är fullt
            }
        }
        else if(p.getDestination().equalsIgnoreCase("Rome") == true){
            planes.get(2).addSeatAndPass(s, passenger);
            boolean full = checkPlane.isPlaneFullyBooked(planes.get(2));

            if(full == true){
                btnAddPass.setEnabled(false);//kan inte boka om planet är fullt
            }
        }
        else if(p.getDestination().equalsIgnoreCase("Miami") == true){
            planes.get(3).addSeatAndPass(s, passenger);
            boolean full = checkPlane.isPlaneFullyBooked(planes.get(3));

            if(full == true){
                btnAddPass.setEnabled(false);//kan inte boka om planet är fullt
            }
        }

        this.setPlanes(planes);
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public ArrayList<Airplane> getPlanes() {
        return planes;
    }

    public void setPlanes(ArrayList<Airplane> planes) {
        this.planes = planes;
    }

    public void setaLine(Airline aLine) {
        this.aLine = aLine;
    }

    private void createUIComponents() {
        String[] orter = {"London", "Paris", "Rome", "Miami"};
        //cboDestination = new JComboBox(orter);
        cboDestination.removeAllItems();
        for (int i = 0; i < 4; i++) {
            cboDestination.addItem(orter[i]);
        }
    }

    public JFrame getGraficalFrame() {
        return graficalFrame;
    }

    public void setGraficalFrame(JFrame graficalFrame) {
        this.graficalFrame = graficalFrame;
    }
    
    //la till dessa 2 feb 2018
//    public AddPForm2 getAPF2() {
//        return apf2;
//    }
//    
//    public void setAPF2(AddPForm2 apf) {
//        this.apf2 = apf;
//    }
    
    //la till dessa april 2018
    public boolean getIfSeatIsBooked(String dest, int sNr) {
        boolean booked = false;
        
        for (Airplane plane : planes) {
            if (plane.getDestination().equals(dest) == true) {
                ArrayList<Seat> seats = plane.getSeats();
                if (seats.get(sNr).isBooked() == true) {
                    booked = true;//return 
                }
                else {
                    booked = false;//return 
                }
            }
        }
        
        return booked;
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPass;
    private javax.swing.JButton btnAirlineInfo;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFlyAirplanes;
    private javax.swing.JComboBox<String> cboDestination;
    private javax.swing.JButton fillPlaneButton;
    private javax.swing.JButton fillPlaneWithRealButton;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
