package graphicalUI;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
//import javax.swing.p
//import javax.swing.JFrame.*;

/**
 *
 * @author Jimmy
 */
public class ProgBarClass extends SwingWorker<Void, Void> { //javax.swing.JFrame

    /**
     * Creates new form ProgBarClass
     */
    public ProgBarClass() {
        //initComponents();
        
        progressClassMainPanel = new JPanel();
        progressBarFlying = new javax.swing.JProgressBar();
        textAreaPlanes = new javax.swing.JTextArea();
        textAreaPlanes.setColumns(25);
        textAreaPlanes.setRows(12);
        textAreaPlanes.setPreferredSize(new java.awt.Dimension(100, 200));//150,50
        
        progressClassMainPanel.add(progressBarFlying);
        progressClassMainPanel.add(textAreaPlanes);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressClassMainPanel = new javax.swing.JPanel();
        progressBarFlying = new javax.swing.JProgressBar();
        textAreaPlanes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        progressClassMainPanel.setLayout(new java.awt.GridLayout(2, 0));
        progressClassMainPanel.add(progressBarFlying);

        textAreaPlanes.setColumns(20);
        textAreaPlanes.setRows(5);
        textAreaPlanes.setPreferredSize(new java.awt.Dimension(150, 50));
        progressClassMainPanel.add(textAreaPlanes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressClassMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressClassMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    */
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progressBarFlying;
    private javax.swing.JPanel progressClassMainPanel;
    private javax.swing.JTextArea textAreaPlanes;
    // End of variables declaration//GEN-END:variables

    @Override
    protected Void doInBackground() throws Exception {
        int seconds = 0;
        //progressBarFlying.setIndeterminate(false);
        for(seconds = 0; seconds < 10; seconds++){
            progressBarFlying.setValue(seconds * 10);
            try{
                Thread.sleep(1000);
            }
            catch (InterruptedException ie){
                ie.printStackTrace();
            }
            textAreaPlanes.setText(textAreaPlanes.getText() + "planes have flown " + (seconds + 1) + " seconds" + "\n");
        }

        return null;
    }

    @Override
    public void done(){
        progressBarFlying.setValue(100);
        JOptionPane.showMessageDialog(null, "Planes arrived at destination!");
    }

    public JPanel getProgressClassMainPanel() {
        return progressClassMainPanel;
    }

}
